### ISSUE TITLE
.h files treated as C instead of C++, even with -xc++ flag added

### ISSUE THREAD

**Issue by skelutten** [MaskRay/vscode-ccls#73] opened 2019-10-09 09:03 UTC
### Observed behavior
I work on a C++ project, where the naming convention of header files is ".h"
To force ccls/clang to treat them as C++ instead of C, I add "-xc++" to settings.json:
    "ccls.clang.extraArgs": [
        "-x c++",
        "-xc++",
        "-std=c++14",
   ..."

But still the headers gets warnings such as "use of undeclared identifier 'std'"

### Expected behavior

The file should be treated as C++

### Steps to reproduce
C++ project with header file named xyz.h using stuf from std::

### System information
/home/$USER/.linuxbrew/Cellar/ccls/0.20190823.3 (5 files, 28.1MB) *
  Built from source on 2019-10-08 at 14:31:57

* OS: 
RedHat
* Editor: 
* vscode-ccls version (`git describe --tags`): 0.1.26

**Comment by joelhock** [comment] 2019-10-10 03:05
i have a feeling this is the same root source as what's causing #74 ; this works fine for me.

**Comment by MaskRay** [comment] 2019-10-10 05:32
Duplicate of #74

My feeling is that you should take a closer look at https://github.com/MaskRay/ccls/wiki/Project-Setup ...

Thanks to Joel.

**Closed by MaskRay** 2019-10-10 05:32 UTC
